SELECT 
    P.PRODUCT_CODE, 
    SUM(OS.SALES_AMOUNT * P.PRICE) AS 'SALES'
FROM OFFLINE_SALE OS
    JOIN PRODUCT P ON OS.PRODUCT_ID = P.PRODUCT_ID
GROUP BY OS.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC
